spring.application.name=SpringBootApiGateway

server.port=${PORT:8080}

spring.mongodb.uri=${MONGODB_URI}

rate-limit.capacity=${RATE_LIMIT_CAPACITY:5}
rate-limit.requests-per-minute=${RATE_LIMIT_REQUESTS_PER_MINUTE:5}