spring.application.name=SpringBootApiGateway

server.port=${PORT:8080}

spring.mongodb.uri=${MONGODB_URI}

jwt.secret-key=${JWT_SECRET_KEY}

rate-limit.capacity=${RATE_LIMIT_CAPACITY:5}
rate-limit.requests-per-minute=${RATE_LIMIT_REQUESTS_PER_MINUTE:5}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=api-gateway